### ISSUE TITLE
remove unused namespaces from response XML

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pycsw#213]
Given all the namespaces we init, the resulting XML output ends being mostly/all namespace declarations in the root element.  Some of which are not required given the context of the request/response.

lxml's `etree.cleanup_namespaces` (http://lxml.de/api/lxml.etree-module.html#cleanup_namespaces) is a convenience function which discards unused namespaces and results in leaner, smarter XML output.

**Comment by tomkralidis** [comment]
Some benchmarks (invoking a `GetCapabilities` request)

|  | size (KB) | average response time based on 10 requests (ms)  |
---- | ------- | ------------ | -- | ---
without `etree.cleanup_namespaces` | 15.37 | 170.4
with `etree.cleanup_namespaces` | 14.67 | 191.2
difference | -4.55%| +10.88%

**Comment by kalxas** [comment]
Thanks for the benchmark @tomkralidis 
I think this slowdown is significant.

**Comment by kalxas** [comment]
Merged in csw3 branch (which will lead to master)
I will keep this ticket open to add a switch in configuration (turning on/off this feature)

**Comment by kalxas** [comment]
This commit has caused problems to CITE testing and has been reverted.

**Comment by tomkralidis** [comment]
There is an issue when using `etree.cleanup_namespaces` against QName type element content:

https://mailman-mail5.webfaction.com/pipermail/lxml/2015-May/007512.html

We need to leave this as is until we find a workaround given CITE testing.

**Comment by kalxas** [comment]
https://github.com/lxml/lxml/pull/167

**Comment by tomkralidis** [comment]
lxml 3.5.0 has been released which [includes](https://github.com/lxml/lxml/blob/master/CHANGES.txt#L25) functionality pycsw can leverage to cover this issue.

@kalxas any objections/concerns to bumping lxml to 3.5.0 in master?

**Comment by kalxas** [comment]
Requiring such new version of lxml might solve this issue, but we should expect the packaging side to have problems: most distributions will take time/years to reach this lxml version.

**Comment by kalxas** [comment]
Anyway, since we are already strict on the versions we require in requirements.txt, it would be fine to bump the lxml version.

**Comment by kalxas** [comment]
@ricardogsilva @tomkralidis it is not that simple.
There are many production deployments that have a hard requirement of deploying debian or rpm packages only: those will remain to previous versions of lxml for a long time.... some of them are still on Python 2.6... you see where this is going :)
Bumping pycsw 2.0 to latest lxml just for one feature is a bit too much IMO.
This is even more difficult to handle when pycsw is deployed as part of CKAN/GeoNode etc. Are we sure CKAN works with bleeding edge lxml? 
In data.gov case, we did not use pip requirements on pycsw because it was breaking ckanext-spatial. Fortunately, pycsw was able to work fine with the versions required by ckanext-spatial...
Same question with GeoNode etc. We do not want to break downstream applications...

A better solution IMO would be to make this feature an option in the configuration so IF someone has lxml 3.5.0 AND wants to enable the namespace cleanup, would be able to do so. What would be the default value of this configuration is another topic :)

**Comment by tomkralidis** [comment]
@kalxas fair enough.  I'm okay with waiting it out a bit to flush out alternatives. Any idea on when lxml 3.5.x would make it to, say, Debian/Ubuntu packaging?

**Comment by kalxas** [comment]
@tomkralidis right now lxml 3.4.4 is in Debian unstable.
https://packages.debian.org/sid/python-lxml
Same for the upcoming Ubuntu LTS Xenial
http://packages.ubuntu.com/source/xenial/lxml
RedHat/CentOS 7: 3.2.1
http://mirror.centos.org/centos/7/os/x86_64/Packages/python-lxml-3.2.1-4.el7.x86_64.rpm
RedHat/CentOS 6: 3.2.3
http://mirror.centos.org/centos/6/os/x86_64/Packages/python-lxml-2.2.3-1.1.el6.x86_64.rpm
SUSE/openSUSE: 3.2.3
https://software.opensuse.org/package/python-lxml

**Comment by tomkralidis** [comment]
Implemented in master.
