### ISSUE TITLE
provide CGI support in unit tests

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pycsw#371]
cc @ricardogsilva 

We should provide CGI support in our unit tests.  Currently the default (and only) approach is via WSGI.

**Comment by tomkralidis** [comment]
@ricardogsilva implemented (but not committed) in #372.  travis-ci reports 2 failures when testing via Python 2.7 in CGI mode:

1. https://travis-ci.org/geopython/pycsw/jobs/76884126#L3380
1. https://travis-ci.org/geopython/pycsw/jobs/76884126#L2998

Any ideas?

**Comment by tomkralidis** [comment]
It looks like the issues above may actually be rooted in a Python bug: https://bugs.python.org/issue24657

**Comment by ricardogsilva** [comment]
Hi @tomkralidis 

I had missed that you were CCing me in this one. I'll take a look at it later. Seems strange that it passes on py2.6 and not on py2.7. Maybe the Python bug you point to.

**Comment by ricardogsilva** [comment]
It seems the tests are failing for two different reasons:

* test on line 3380, `suites/cite/get/requests.txt:6c375703-9c00-4aef-bec7-d2e964f849eb` fails with:

  ```
  Invalid outputschema parameter http:/www.w3.org/2005/Atom
  ```

  This indeed seems related to the Python bug mentioned by @tomkralidis as the outputschema URL is wrongfully stripped of some `/` characters

* test on line 2998, suites/default/get/requests.txt:GetRecords-filter fails with:

  ```
  Invalid Filter query: Exception: document not valid.
  Error: line 1: Start tag expected, '&lt;' not found.
  ```

  This means that `lxml.etree` is not able to parse the input filter constraint. This seems to be due to the fact that the request's constraint is already quoted and pycsw is quoting it again somewhere in the process. Request is:

  ```
  GetRecords-filter,PYCSW_SERVER?
      config=tests/suites/default/default.cfg&
      service=CSW&
      version=2.0.2&
      request=GetRecords&
      typenames=csw:Record&
      elementsetname=full&
      resulttype=results&
      constraintlanguage=FILTER&
      constraint=%3Cogc%3AFilter%20xmlns%3Aogc%3D%22http%3A%2F%2Fwww.opengis.net%2Fogc%22%3E%3Cogc%3APropertyIsEqualTo%3E%3Cogc%3APropertyName%3Edc%3Atitle%3C%2Fogc%3APropertyName%3E%3Cogc%3ALiteral%3ELorem%20ipsum%3C%2Fogc%3ALiteral%3E%3C%2Fogc%3APropertyIsEqualTo%3E%3C%2Fogc%3AFilter%3E
  ```

  It seems that somewhere in the pipeline, the incoming constraint (which is already quoted) is being quoted again.
  Line 264 of `pycsw.server` performs an `urllib.unquote` on the constraint, which should result in correct parsing. However, unquoting the  (by now double quoted) constraint string is equal to the original (quoted) input string. I have not been able to determine where this double quoting happens yet. Maybe in urllib2's `Request` call in `pycsw.core.util.http_request()`? or perhaps in `urllib2.urlopen()`?

  Anyway it seems that this may indeed also be related to the same Python bug. 

Things that we could consider:

  * changing the original test to provide an unquoted request
  * ditching urllib2 and start using the [requests](http://requests.readthedocs.org/en/latest/) library, which is now the defacto standard for dealing with HTTP in Python ([even the official docs recommend it](https://docs.python.org/2/library/urllib2.html)). This could potentially solve both failures (I have not tried it yet)

**Comment by tomkralidis** [comment]
Thanks @ricardogsilva.  Moving to `requests` is an additional dependency.  Which is not a bad thing given `requests` is the goto http lib for Python, and has packaging support.  @kalxas interested in your comments.

**Comment by kalxas** [comment]
Switching to `requests` sounds like a good plan, especially for the Python 3 support (which splits the urllib)

**Comment by tomkralidis** [comment]
+1 for moving to requests.

**Comment by tomkralidis** [comment]
Looking deeper, let's make sure moving to requests will solve the above issue.

**Comment by tomkralidis** [comment]
@ricardogsilva I've put forth #455 awhile back, which now needs an update given updates to our testing framework. Any ideas/thoughts on making this work via pytest/tox?

**Comment by tomkralidis** [comment]
@ricardogsilva thoughts on this one?  Is CGI still relevant for a testing context?
