### ISSUE TITLE
fix version convention in dev

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pycsw#535]
# Description

Since moving to [setuptools](https://github.com/geopython/pycsw/commit/4eb9a3320509d791d4619199c832d4481c3813f7) in `setup.py`, the following results when trying to build pycsw: 

```bash
mandalor:/home/tkralidi/Dev/pycsw/pycsw-tomkralidis# python setup.py build
/usr/local/lib/python2.7/site-packages/setuptools/dist.py:334: UserWarning: Normalizing '2.1.0-dev
' to '2.1.0.dev0' normalized_version,
```

This was originally brought up during https://github.com/geopython/pycsw/pull/524/commits/4eb9a3320509d791d4619199c832d4481c3813f7#r120224942 by @ricardogsilva

In master, we always keep a `VERSION.txt` specified as `x.y-dev`, where `x` is the major version and `y` is the minor version.  `y` is always an odd number as per the producingoss.com [even/odd strategy](http://producingoss.com/en/development-cycle.html#release-number-even-odd-strategy).  `VERSION.txt` is only updated when making releases (which are then tagged, and the `VERSION.txt` in master goes back to `x.y-dev`).

We need to settle on a versioning convention (`x.y.dev0` ? Other ideas?) for when in development given the setuptools warning.  Our formal release versions should be unaffected.

In addition, since `setup.py` now uses `VERSION.txt` directly we should ensure that reading it strips all spaces before using (i.e. update https://github.com/geopython/pycsw/blob/master/setup.py#L42 to `contents = fh.read().strip()`).

# Environment

- operating system: all
- Python version: 2/3
- pycsw version: master
- source/distribution
  - [x] git clone
  - [ ] DebianGIS/UbuntuGIS
  - [ ] PyPI
  - [ ] zip/tar.gz
  - [ ] other (please specify):
- web server
  - [ ] Apache/mod_wsgi
  - [ ] CGI
  - [ ] other (please specify): 

# Steps to Reproduce
`python setup.py build`
# Additional Information

**Comment by ricardogsilva** [comment]
### Some more context

Python's conventions for specifying versions are described in [PEP440](https://www.python.org/dev/peps/pep-0440/). This is followed by `pip` and `setuptools` and subsequently by `pkg_resources` (which is part of setuptools), which we're using in order to read the version at runtime.

According to the PEP, the scheme `major.minor-dev`, which we are using for dev releases, [is perfectly valid](https://www.python.org/dev/peps/pep-0440/#development-release-separators). The PEP states that there is a normalization process that transforms `major.minor-dev` into `major.minor.dev0` and states that this is done in order to ensure compatibility with other formats.


### Our current versioning scheme

IMHO there doesn't seem to be a problem here. We can keep using the same versioning format as before. The only thing to be aware of is that python normalizes the dev version to `major.minor.devnumber` (with number being zero if not specified). This means that when installing a dev release of pycsw, if one runs the following:

```python
>>> import pycsw
>>> pycsw.__version__
2.1.dev0
```

The result is slightly different from what is actually written in the `VERSION.txt` file:

```bash
$ cat VERSION.txt
2.1-dev
```

However, semantically speaking, both refer to the exact same version.


### About possible whitespaces in the version file

As for the whitespace concern, the PEP [has this case covered too](https://www.python.org/dev/peps/pep-0440/#id43), by stating that any leading and trailing whitespace must be ignored when determining the version. This means that we don't really need to trim the whitespace when reading the file in `setup.py`.


### should we further distinguish one dev build from another?

Now we could further argue that if I install a dev version now, then someone makes a couple of commits to master and then I install a dev version again, then the two dev versions will be different while still having the same version identifier. Should we consider this a problem?

It seems to me that we could address this by including the git revision number in the dev versions. there seems to be a way to do this by using `git describe`. A possible implementation might take something from each of these links:

https://stackoverflow.com/questions/14989858/get-the-current-git-hash-in-a-python-script
https://github.com/numpy/numpy/blob/master/setup.py#L70-L92

Personally I think this is something that we could eventually implement, but I don't see it as a priority, nor am I motivated at present to work on it.

What do you think?

**Comment by tomkralidis** [comment]
@ricardogsilva thanks for the (as always) deep and thorough feedback. Sounds like we should leave this as is then. Perhaps stripping the whitespace is a good safeguard regardless? Objections?

**Comment by kalxas** [comment]
Thanks @ricardogsilva 
Lets leave that as is for now and use the git hash in the future.
